-- ═══════════════════════════════════════════════════════════════
-- Phase 1 Seed: Kitchens, Locations, and Menu Items
-- Derived from src/data/mockData.ts and src/data/masterMenuData.ts
-- 10 kitchen_partners × 5-7 items each → 57 instant_menu_items
-- 10 kitchen_partner_locations (US cities with lat/lng)
-- kitchen_categories seeded for category filter
-- app_config: kitchen_visibility_radius + invoice_settings
-- ═══════════════════════════════════════════════════════════════

-- ── 1. Kitchen Partners ──────────────────────────────────────────
INSERT INTO public.kitchen_partners
  (id, partner_id, name, image, rating, review_count, cuisine, delivery_time, min_order,
   is_branded, location, is_veg, food_preference, is_attendance_marked, attendance_slot, is_active)
VALUES
  ('SKID-NYC-001', 'P-001',
   'Shero Kitchen – Manhattan (Veg)',
   'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=300&fit=crop',
   4.6, 342, ARRAY['South Indian','North Indian'], '30-45 min', 2,
   true, 'Manhattan, NY', true, 'veg', true, 'Morning (6-10 AM)', true),

  ('SKID-NYC-002', 'P-001',
   'Shero Kitchen – Manhattan (Non-Veg)',
   'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=400&h=300&fit=crop',
   4.6, 342, ARRAY['South Indian','North Indian'], '30-45 min', 2,
   true, 'Manhattan, NY', false, 'nonveg', true, 'Morning (6-10 AM)', true),

  ('SKID-SF-003', 'P-002',
   'Padma''s Home Kitchen',
   'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=400&h=300&fit=crop',
   4.8, 215, ARRAY['South Indian','Andhra'], '40-55 min', 1,
   false, 'San Francisco, CA', true, 'veg', true, 'Lunch (10 AM-2 PM)', true),

  ('SKID-AUS-004', 'P-003',
   'Shero Kitchen – Austin (Veg)',
   'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&h=300&fit=crop',
   4.5, 189, ARRAY['South Indian','Chinese'], '25-40 min', 2,
   true, 'Austin, TX', true, 'veg', true, 'Morning (6-10 AM)', true),

  ('SKID-AUS-005', 'P-003',
   'Shero Kitchen – Austin (Non-Veg)',
   'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=400&h=300&fit=crop',
   4.5, 189, ARRAY['South Indian','Chinese'], '25-40 min', 2,
   true, 'Austin, TX', false, 'nonveg', false, '', true),

  ('SKID-CHI-006', 'P-004',
   'Anitha''s Flavours',
   'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop',
   4.9, 87, ARRAY['Andhra','South Indian'], '45-60 min', 1,
   false, 'Chicago, IL', false, 'both', false, '', true),

  ('SKID-HOU-007', 'P-005',
   'Shero Kitchen – Houston (Veg)',
   'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400&h=300&fit=crop',
   4.4, 156, ARRAY['South Indian','North Indian'], '30-45 min', 2,
   true, 'Houston, TX', true, 'veg', true, 'Morning (6-10 AM)', true),

  ('SKID-SEA-008', 'P-006',
   'Radha''s Kitchen',
   'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
   4.7, 64, ARRAY['Kerala','South Indian'], '50-65 min', 1,
   false, 'Seattle, WA', true, 'veg', true, 'Lunch (10 AM-2 PM)', true),

  ('SKID-DAL-009', 'P-007',
   'Shero Kitchen – Dallas (Veg)',
   'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=400&h=300&fit=crop',
   4.3, 98, ARRAY['South Indian','North Indian'], '35-50 min', 2,
   true, 'Dallas, TX', true, 'veg', true, 'Morning (6-10 AM)', true),

  ('SKID-NJ-010', 'P-008',
   'Fatima''s Biryani House',
   'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&h=300&fit=crop',
   4.8, 234, ARRAY['Mughlai','Hyderabadi'], '40-55 min', 2,
   false, 'Jersey City, NJ', false, 'nonveg', false, '', true)

ON CONFLICT (id) DO UPDATE SET
  name            = EXCLUDED.name,
  image           = EXCLUDED.image,
  rating          = EXCLUDED.rating,
  review_count    = EXCLUDED.review_count,
  cuisine         = EXCLUDED.cuisine,
  delivery_time   = EXCLUDED.delivery_time,
  min_order       = EXCLUDED.min_order,
  is_branded      = EXCLUDED.is_branded,
  location        = EXCLUDED.location,
  is_veg          = EXCLUDED.is_veg,
  food_preference = EXCLUDED.food_preference,
  is_attendance_marked = EXCLUDED.is_attendance_marked,
  attendance_slot = EXCLUDED.attendance_slot,
  is_active       = EXCLUDED.is_active;

-- ── 2. Kitchen Partner Locations (lat/lng for geofencing) ────────
INSERT INTO public.kitchen_partner_locations
  (kitchen_id, partner_name, partner_phone, pincode, latitude, longitude, location, is_active, is_attendance_marked, attendance_slot)
VALUES
  ('SKID-NYC-001','Lakshmi Devi',   '+12125550101','10001', 40.7506, -73.9971, 'Manhattan, NY',    true, true,  'Morning (6-10 AM)'),
  ('SKID-NYC-002','Lakshmi Devi',   '+12125550101','10001', 40.7506, -73.9971, 'Manhattan, NY',    true, true,  'Morning (6-10 AM)'),
  ('SKID-SF-003', 'Padma Reddy',    '+14155550102','94103', 37.7749, -122.4194,'San Francisco, CA',true, true,  'Lunch (10 AM-2 PM)'),
  ('SKID-AUS-004','Kavitha Sharma', '+15125550103','78701', 30.2672, -97.7431, 'Austin, TX',       true, true,  'Morning (6-10 AM)'),
  ('SKID-AUS-005','Kavitha Sharma', '+15125550103','78701', 30.2672, -97.7431, 'Austin, TX',       true, false, ''),
  ('SKID-CHI-006','Anitha Kumari',  '+13125550104','60601', 41.8781, -87.6298, 'Chicago, IL',      true, false, ''),
  ('SKID-HOU-007','Sunitha Rao',    '+17135550105','77002', 29.7604, -95.3698, 'Houston, TX',      true, true,  'Morning (6-10 AM)'),
  ('SKID-SEA-008','Radha Menon',    '+12065550106','98101', 47.6062, -122.3321,'Seattle, WA',      true, true,  'Lunch (10 AM-2 PM)'),
  ('SKID-DAL-009','Meena Iyer',     '+14695550107','75201', 32.7767, -96.7970, 'Dallas, TX',       true, true,  'Morning (6-10 AM)'),
  ('SKID-NJ-010', 'Fatima Brown',   '+13105550108','07302', 40.7178, -74.0431, 'Jersey City, NJ',  true, false, '')

ON CONFLICT DO NOTHING;

-- ── 3. Instant Menu Items ────────────────────────────────────────
-- SKID-NYC-001 : Shero Manhattan Veg (6 items)
INSERT INTO public.instant_menu_items
  (id, kitchen_id, name, description, price, ppp, image, category,
   is_veg, is_bestseller, spice_level, serving_size, preparation_time,
   ingredients, major_vegetables, allergens, nutrition_info, is_toggled_on, add_ons, is_active)
VALUES

('m1','SKID-NYC-001','Ghee Rice with Dal Tadka',
 'Fragrant basmati rice cooked in pure ghee, served with creamy yellow dal tempered with cumin and garlic.',
 15, 10, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'Rice', true, false, 'mild', 'Serves 1', '20 min',
 ARRAY['Basmati Rice','Ghee','Toor Dal','Cumin','Garlic','Turmeric'],
 ARRAY['Onion','Tomato'], ARRAY['Dairy'],
 '{"calories":480,"protein":"14g","carbs":"72g","fat":"16g"}', true,
 '[{"id":"a1-1","name":"Extra Ghee","price":2,"isVeg":true},{"id":"a1-2","name":"Papad (2 pcs)","price":2,"isVeg":true},{"id":"a1-3","name":"Pickle","price":1,"isVeg":true},{"id":"a1-4","name":"Raita","price":2,"isVeg":true}]',
 true),

('m2','SKID-NYC-001','Masala Dosa',
 'Crispy golden dosa filled with spiced potato masala, served with coconut chutney and sambar.',
 10, 6, 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=600&h=400&fit=crop',
 'Dosa', true, true, 'medium', 'Serves 1', '15 min',
 ARRAY['Rice Batter','Urad Dal','Potatoes','Onions','Mustard Seeds'],
 ARRAY['Potato','Onion'], ARRAY[]::text[],
 '{"calories":350,"protein":"8g","carbs":"58g","fat":"10g"}', true,
 '[{"id":"a2-1","name":"Extra Chutney","price":1,"isVeg":true},{"id":"a2-2","name":"Extra Sambar","price":2,"isVeg":true},{"id":"a2-3","name":"Cheese Topping","price":3,"isVeg":true},{"id":"a2-4","name":"Ghee Roast","price":2,"isVeg":true}]',
 true),

('m3','SKID-NYC-001','Paneer Butter Masala',
 'Soft paneer cubes in a velvety tomato-cashew gravy.',
 19, 12, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
 'Curries', true, false, 'mild', 'Serves 1-2', '25 min',
 ARRAY['Paneer','Tomatoes','Cashews','Cream','Butter','Spices'],
 ARRAY['Tomato','Capsicum'], ARRAY['Dairy','Nuts'],
 '{"calories":460,"protein":"18g","carbs":"14g","fat":"36g"}', true,
 '[{"id":"a3-1","name":"Extra Paneer","price":4,"isVeg":true},{"id":"a3-2","name":"Butter Naan","price":4,"isVeg":true},{"id":"a3-3","name":"Jeera Rice","price":4,"isVeg":true}]',
 true),

('m16','SKID-NYC-001','Chinna Vengayam Sambar',
 'Sambar full of little tiny, juicy, tamarind-soaked purple shallots — Chettinad style.',
 12, 7, 'https://sherohomeerp-shero.s3.ap-south-1.amazonaws.com/catalog/items/1719484899_667d41e369b8a.jpg',
 'Sambar', true, false, 'medium', 'Serves 1-2 (450 ml)', '25 min',
 ARRAY['Shallots','Toor Dal','Tamarind','Tomato','Spices'],
 ARRAY['Shallots','Dal/Lentils','Tamarind'], ARRAY[]::text[],
 '{"calories":190,"protein":"9g","carbs":"28g","fat":"5g"}', true,
 '[{"id":"a16-1","name":"Extra Sambar","price":2,"isVeg":true}]',
 true),

('m17','SKID-NYC-001','Vendaikai Kara Kuzhambu',
 'Spicy, tangy South Indian okra curry with tamarind, coconut & aromatic spices.',
 14, 8, 'https://sherohomeerp-shero.s3.ap-south-1.amazonaws.com/catalog/items/1719486129_667d46b1608b3.jpg',
 'Kara Kuzhambu', true, false, 'hot', 'Serves 1-2 (450 ml)', '30 min',
 ARRAY['Okra','Tamarind','Coconut','Shallots','Curry Leaves'],
 ARRAY['Okra','Tamarind','Coconut'], ARRAY[]::text[],
 '{"calories":210,"protein":"4g","carbs":"22g","fat":"12g"}', true,
 '[]',
 true),

('m18','SKID-NYC-001','Carrot Beans Poriyal',
 'Colorful stir fry of boiled carrot & beans with grated coconut.',
 9, 5, 'https://sherohomeerp-shero.s3.ap-south-1.amazonaws.com/catalog/items/1719487022_667d4a2e13758.jpg',
 'Poriyal', true, false, 'mild', '250 g', '15 min',
 ARRAY['Carrot','Beans','Coconut','Mustard Seeds','Curry Leaves'],
 ARRAY['Carrot','Beans','Coconut'], ARRAY[]::text[],
 '{"calories":160,"protein":"4g","carbs":"18g","fat":"8g"}', true,
 '[]',
 true),

-- SKID-NYC-002 : Shero Manhattan Non-Veg (5 items)
('m4','SKID-NYC-002','Hyderabadi Chicken Biryani',
 'Aromatic basmati rice layered with tender chicken, saffron, and Hyderabadi spices.',
 25, 16, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
 'Biryani', false, true, 'medium', 'Serves 1-2', '25 min',
 ARRAY['Basmati Rice','Chicken','Onions','Yogurt','Saffron','Mint','Spices'],
 ARRAY['Onion','Tomato','Mint'], ARRAY['Dairy'],
 '{"calories":650,"protein":"32g","carbs":"78g","fat":"22g"}', true,
 '[{"id":"a4-1","name":"Extra Raita","price":2,"isVeg":true},{"id":"a4-2","name":"Boiled Egg (2 pcs)","price":2,"isVeg":false},{"id":"a4-3","name":"Mirchi Ka Salan","price":3,"isVeg":true},{"id":"a4-4","name":"Extra Chicken","price":5,"isVeg":false}]',
 true),

('m5','SKID-NYC-002','Butter Chicken',
 'Tender chicken pieces in a rich, creamy tomato-butter gravy.',
 22, 14, 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
 'Curries', false, true, 'mild', 'Serves 1-2', '30 min',
 ARRAY['Chicken','Tomatoes','Butter','Cream','Cashews','Spices'],
 ARRAY['Tomato','Onion'], ARRAY['Dairy','Nuts'],
 '{"calories":520,"protein":"28g","carbs":"12g","fat":"38g"}', true,
 '[{"id":"a5-1","name":"Butter Naan","price":4,"isVeg":true},{"id":"a5-2","name":"Rumali Roti","price":2,"isVeg":true},{"id":"a5-3","name":"Jeera Rice","price":4,"isVeg":true}]',
 true),

('m19','SKID-NYC-002','Mutton Rogan Josh',
 'Classic Kashmiri mutton curry slow-cooked with whole spices and yogurt.',
 28, 18, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
 'Curries', false, false, 'medium', 'Serves 1-2', '40 min',
 ARRAY['Mutton','Yogurt','Kashmiri Chili','Whole Spices','Onion','Ginger'],
 ARRAY['Onion'], ARRAY['Dairy'],
 '{"calories":580,"protein":"35g","carbs":"10g","fat":"42g"}', true,
 '[{"id":"a19-1","name":"Basmati Rice","price":4,"isVeg":true},{"id":"a19-2","name":"Butter Naan","price":4,"isVeg":true}]',
 true),

('m20','SKID-NYC-002','Egg Masala Curry',
 'Hard-boiled eggs simmered in a spicy onion-tomato masala.',
 16, 10, 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
 'Curries', false, false, 'medium', 'Serves 1', '20 min',
 ARRAY['Eggs','Onion','Tomato','Spices','Curry Leaves'],
 ARRAY['Onion','Tomato'], ARRAY['Eggs'],
 '{"calories":340,"protein":"16g","carbs":"12g","fat":"24g"}', true,
 '[{"id":"a20-1","name":"Steamed Rice","price":3,"isVeg":true}]',
 true),

('m21','SKID-NYC-002','Keema Pulao',
 'Fragrant rice cooked with spiced minced chicken and whole spices.',
 20, 13, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'Rice', false, false, 'medium', 'Serves 1', '25 min',
 ARRAY['Basmati Rice','Minced Chicken','Onion','Ginger','Garlic','Whole Spices'],
 ARRAY['Onion','Peas'], ARRAY[]::text[],
 '{"calories":490,"protein":"24g","carbs":"62g","fat":"16g"}', true,
 '[{"id":"a21-1","name":"Raita","price":2,"isVeg":true}]',
 true),

-- SKID-SF-003 : Padma's Home Kitchen (6 items)
('m6','SKID-SF-003','Curd Rice',
 'Comforting South Indian curd rice tempered with mustard seeds, curry leaves, and green chillies.',
 8, 5, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
 'Rice', true, true, 'mild', 'Serves 1', '10 min',
 ARRAY['Rice','Curd','Mustard Seeds','Curry Leaves','Green Chillies'],
 ARRAY[]::text[], ARRAY['Dairy'],
 '{"calories":320,"protein":"10g","carbs":"56g","fat":"6g"}', true,
 '[]',
 true),

('m7','SKID-SF-003','Sambar Rice Combo',
 'Steamed rice with piping hot sambar, papad, pickle, and a side of kootu curry.',
 12, 8, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'Rice', true, false, 'medium', 'Serves 1', '20 min',
 ARRAY['Rice','Toor Dal','Mixed Vegetables','Tamarind','Sambar Powder'],
 ARRAY['Drumstick','Carrot','Beans'], ARRAY[]::text[],
 '{"calories":420,"protein":"12g","carbs":"68g","fat":"8g"}', true,
 '[]',
 true),

('m8','SKID-SF-003','Pesarattu (Green Gram Dosa)',
 'Healthy Andhra-style green gram dosa served with ginger chutney.',
 9, 6, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop',
 'Dosa', true, false, 'mild', 'Serves 1', '15 min',
 ARRAY['Green Gram','Rice','Ginger','Green Chillies'],
 ARRAY['Onion'], ARRAY[]::text[],
 '{"calories":280,"protein":"12g","carbs":"44g","fat":"6g"}', false,
 '[]',
 true),

('m22','SKID-SF-003','Avial',
 'Mixed vegetables cooked in a coconut-yogurt gravy — classic Kerala dish.',
 11, 7, 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=600&h=400&fit=crop',
 'Curry', true, false, 'mild', 'Serves 1-2 (450 ml)', '30 min',
 ARRAY['Drumstick','Carrot','Beans','Coconut','Yogurt','Curry Leaves'],
 ARRAY['Drumstick','Carrot','Beans','Coconut','Curd/Buttermilk'], ARRAY['Dairy'],
 '{"calories":210,"protein":"5g","carbs":"24g","fat":"11g"}', true,
 '[]',
 true),

('m23','SKID-SF-003','Gutti Vankaya Kura',
 'Stuffed baby brinjal curry with peanut & sesame — Andhra specialty.',
 13, 8, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Curry', true, false, 'hot', 'Serves 1-2 (450 ml)', '30 min',
 ARRAY['Brinjal','Peanuts','Sesame','Onion','Tamarind','Spices'],
 ARRAY['Brinjal','Onion','Tamarind'], ARRAY['Nuts'],
 '{"calories":245,"protein":"7g","carbs":"19g","fat":"16g"}', true,
 '[]',
 true),

('m24','SKID-SF-003','Gongura Pachadi',
 'Tangy Andhra sorrel leaves chutney with roasted red chilies and garlic.',
 7, 4, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=400&fit=crop',
 'Chutney', true, false, 'hot', '200 g', '15 min',
 ARRAY['Gongura Leaves','Red Chili','Garlic','Onion','Mustard Seeds'],
 ARRAY['Onion','Garlic'], ARRAY[]::text[],
 '{"calories":90,"protein":"2g","carbs":"10g","fat":"5g"}', true,
 '[]',
 true),

-- SKID-AUS-004 : Shero Austin Veg (5 items)
('m9','SKID-AUS-004','Veg Fried Rice',
 'Wok-tossed basmati rice with vegetables, soy sauce, and Indo-Chinese spices.',
 14, 9, 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=400&fit=crop',
 'Chinese', true, true, 'medium', 'Serves 1', '20 min',
 ARRAY['Rice','Mixed Vegetables','Soy Sauce','Spring Onions'],
 ARRAY['Carrot','Beans','Capsicum'], ARRAY['Soy'],
 '{"calories":420,"protein":"10g","carbs":"64g","fat":"14g"}', true,
 '[]',
 true),

('m10','SKID-AUS-004','Idli Sambar (4 pcs)',
 'Soft steamed idlis served with classic sambar and coconut chutney.',
 7, 4, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop',
 'Idli', true, false, 'mild', '4 pieces', '15 min',
 ARRAY['Rice','Urad Dal','Fenugreek Seeds'],
 ARRAY[]::text[], ARRAY[]::text[],
 '{"calories":280,"protein":"8g","carbs":"52g","fat":"4g"}', true,
 '[{"id":"a10-1","name":"Extra Chutney","price":1,"isVeg":true},{"id":"a10-2","name":"Extra Sambar","price":2,"isVeg":true}]',
 true),

('m25','SKID-AUS-004','Bisi Bele Bath',
 'Spiced rice cooked with lentils and mixed vegetables — Udupi classic.',
 11, 7, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'Rice', true, false, 'medium', '350 g', '30 min',
 ARRAY['Rice','Toor Dal','Mixed Vegetables','Tamarind','Ghee','Bisi Bele Bath Powder'],
 ARRAY['Dal/Lentils','Carrot','Beans','Tamarind'], ARRAY['Dairy'],
 '{"calories":380,"protein":"12g","carbs":"62g","fat":"10g"}', true,
 '[{"id":"a25-1","name":"Boondi Raita","price":2,"isVeg":true}]',
 true),

('m26','SKID-AUS-004','Dal Makhani',
 'Slow-cooked black lentils in creamy tomato gravy — North Indian comfort food.',
 16, 10, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'Dal', true, false, 'mild', 'Serves 1-2 (450 ml)', '25 min',
 ARRAY['Black Lentils','Kidney Beans','Butter','Cream','Tomatoes','Spices'],
 ARRAY['Tomato'], ARRAY['Dairy'],
 '{"calories":440,"protein":"18g","carbs":"38g","fat":"24g"}', true,
 '[{"id":"a26-1","name":"Butter Naan","price":4,"isVeg":true},{"id":"a26-2","name":"Jeera Rice","price":4,"isVeg":true}]',
 true),

('m27','SKID-AUS-004','Aloo Gobi',
 'Dry potato & cauliflower sabzi with cumin and turmeric — North Indian home style.',
 12, 7, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Sabzi', true, false, 'mild', '250 g', '20 min',
 ARRAY['Potato','Cauliflower','Tomato','Cumin','Turmeric','Coriander'],
 ARRAY['Potato','Cauliflower','Tomato'], ARRAY[]::text[],
 '{"calories":230,"protein":"5g","carbs":"32g","fat":"9g"}', true,
 '[]',
 true),

-- SKID-AUS-005 : Shero Austin Non-Veg (5 items)
('m28','SKID-AUS-005','Chettinad Chicken Curry',
 'Fiery South Indian chicken curry with freshly ground Chettinad spices and coconut.',
 20, 13, 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
 'Curries', false, true, 'hot', 'Serves 1-2', '35 min',
 ARRAY['Chicken','Coconut','Chettinad Spices','Shallots','Curry Leaves'],
 ARRAY['Shallots','Coconut'], ARRAY[]::text[],
 '{"calories":480,"protein":"30g","carbs":"14g","fat":"34g"}', true,
 '[{"id":"a28-1","name":"Steamed Rice","price":3,"isVeg":true}]',
 true),

('m29','SKID-AUS-005','Fish Fry (2 pcs)',
 'Crispy pan-fried fish marinated in South Indian spices and curry leaves.',
 18, 11, 'https://images.unsplash.com/photo-1626776876729-bab4369a5a5a?w=600&h=400&fit=crop',
 'Fry', false, false, 'medium', '2 pieces', '25 min',
 ARRAY['Fish','Turmeric','Red Chili','Curry Leaves','Ginger','Garlic'],
 ARRAY[]::text[], ARRAY['Fish'],
 '{"calories":310,"protein":"26g","carbs":"8g","fat":"18g"}', true,
 '[{"id":"a29-1","name":"Coconut Chutney","price":1,"isVeg":true}]',
 true),

('m30','SKID-AUS-005','Prawn Masala',
 'Juicy prawns cooked in a spiced onion-tomato gravy with coconut milk.',
 24, 15, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
 'Curries', false, false, 'medium', 'Serves 1-2', '30 min',
 ARRAY['Prawns','Onion','Tomato','Coconut Milk','Spices'],
 ARRAY['Onion','Tomato'], ARRAY['Shellfish','Coconut'],
 '{"calories":360,"protein":"28g","carbs":"12g","fat":"22g"}', true,
 '[{"id":"a30-1","name":"Appam (2 pcs)","price":3,"isVeg":true},{"id":"a30-2","name":"Steamed Rice","price":3,"isVeg":true}]',
 true),

('m31','SKID-AUS-005','Chicken Biryani',
 'Aromatic dum biryani with marinated chicken and caramelised onions.',
 22, 14, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
 'Biryani', false, true, 'medium', 'Serves 1-2', '30 min',
 ARRAY['Basmati Rice','Chicken','Yogurt','Saffron','Fried Onions','Mint'],
 ARRAY['Onion','Mint'], ARRAY['Dairy'],
 '{"calories":620,"protein":"30g","carbs":"74g","fat":"20g"}', true,
 '[{"id":"a31-1","name":"Raita","price":2,"isVeg":true},{"id":"a31-2","name":"Mirchi Ka Salan","price":3,"isVeg":true}]',
 true),

('m32','SKID-AUS-005','Mutton Pepper Curry',
 'Tender mutton cooked with freshly ground black pepper and South Indian spices.',
 26, 17, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'Curries', false, false, 'hot', 'Serves 1-2', '45 min',
 ARRAY['Mutton','Black Pepper','Onion','Curry Leaves','Coconut'],
 ARRAY['Onion','Coconut'], ARRAY[]::text[],
 '{"calories":540,"protein":"34g","carbs":"8g","fat":"40g"}', true,
 '[{"id":"a32-1","name":"Parotta (2 pcs)","price":3,"isVeg":true}]',
 true),

-- SKID-CHI-006 : Anitha's Flavours (5 items)
('m33','SKID-CHI-006','Andhra Chicken Curry',
 'Spicy Andhra-style chicken curry with roasted coconut and tamarind.',
 21, 13, 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&h=400&fit=crop',
 'Curries', false, true, 'hot', 'Serves 1-2', '35 min',
 ARRAY['Chicken','Coconut','Tamarind','Red Chili','Onion','Spices'],
 ARRAY['Onion','Coconut','Tamarind'], ARRAY[]::text[],
 '{"calories":460,"protein":"30g","carbs":"16g","fat":"30g"}', true,
 '[{"id":"a33-1","name":"Steamed Rice","price":3,"isVeg":true}]',
 true),

('m34','SKID-CHI-006','Bendakaya Vepudu',
 'Crispy okra fry with Andhra-style spices — served as a side.',
 10, 6, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Fry', true, false, 'medium', '250 g', '20 min',
 ARRAY['Okra','Onion','Red Chili','Mustard Seeds','Curry Leaves'],
 ARRAY['Okra','Onion'], ARRAY[]::text[],
 '{"calories":170,"protein":"3g","carbs":"16g","fat":"10g"}', true,
 '[]',
 true),

('m35','SKID-CHI-006','Pappu Dal',
 'Andhra-style toor dal with tomato tempering and ghee.',
 9, 5, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'Dal', true, false, 'mild', 'Serves 1-2 (450 ml)', '20 min',
 ARRAY['Toor Dal','Tomato','Onion','Ghee','Mustard Seeds','Curry Leaves'],
 ARRAY['Dal/Lentils','Tomato'], ARRAY['Dairy'],
 '{"calories":220,"protein":"11g","carbs":"30g","fat":"7g"}', false,
 '[]',
 true),

('m36','SKID-CHI-006','Egg Biryani',
 'Aromatic basmati rice layered with spiced boiled eggs and fried onions.',
 17, 10, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
 'Biryani', false, false, 'medium', 'Serves 1', '25 min',
 ARRAY['Basmati Rice','Eggs','Fried Onions','Mint','Saffron','Whole Spices'],
 ARRAY['Onion','Mint'], ARRAY['Eggs','Dairy'],
 '{"calories":510,"protein":"18g","carbs":"70g","fat":"18g"}', true,
 '[{"id":"a36-1","name":"Raita","price":2,"isVeg":true}]',
 true),

('m37','SKID-CHI-006','Pesarattu',
 'Andhra green moong dal crepe — crispy and light, served with ginger chutney.',
 8, 5, 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&h=400&fit=crop',
 'Breakfast', true, false, 'mild', 'Serves 1 (2 pcs)', '20 min',
 ARRAY['Green Gram','Rice','Ginger','Green Chillies','Onion'],
 ARRAY['Dal/Lentils','Onion'], ARRAY[]::text[],
 '{"calories":240,"protein":"10g","carbs":"36g","fat":"6g"}', true,
 '[{"id":"a37-1","name":"Upma (side)","price":3,"isVeg":true}]',
 true),

-- SKID-HOU-007 : Shero Houston Veg (5 items)
('m11','SKID-HOU-007','Aloo Paratha with Curd',
 'Crispy stuffed aloo paratha with fresh curd and pickle.',
 11, 7, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
 'Paratha', true, true, 'mild', '2 pieces', '15 min',
 ARRAY['Wheat Flour','Potatoes','Spices','Curd'],
 ARRAY['Potato','Onion'], ARRAY['Dairy','Gluten'],
 '{"calories":390,"protein":"10g","carbs":"52g","fat":"16g"}', true,
 '[]',
 true),

('m38','SKID-HOU-007','Rajma Chawal',
 'Red kidney beans in a spiced tomato gravy, served with steamed basmati rice.',
 13, 8, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'North Indian', true, true, 'medium', 'Serves 1', '25 min',
 ARRAY['Kidney Beans','Basmati Rice','Tomato','Onion','Spices'],
 ARRAY['Tomato','Onion'], ARRAY[]::text[],
 '{"calories":460,"protein":"16g","carbs":"72g","fat":"10g"}', true,
 '[{"id":"a38-1","name":"Pickle","price":1,"isVeg":true},{"id":"a38-2","name":"Papad","price":1,"isVeg":true}]',
 true),

('m39','SKID-HOU-007','Chole Bhature',
 'Spicy chickpea curry with fluffy fried bhatura bread.',
 13, 8, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'North Indian', true, true, 'medium', 'Serves 1', '20 min',
 ARRAY['Chickpeas','Flour','Onions','Tomatoes','Spices'],
 ARRAY['Onion','Tomato'], ARRAY['Gluten'],
 '{"calories":520,"protein":"16g","carbs":"62g","fat":"22g"}', true,
 '[{"id":"a39-1","name":"Extra Chole","price":3,"isVeg":true}]',
 true),

('m40','SKID-HOU-007','Palak Paneer',
 'Cottage cheese cubes in a smooth spiced spinach gravy.',
 17, 11, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
 'Curries', true, false, 'mild', 'Serves 1-2', '25 min',
 ARRAY['Paneer','Spinach','Onion','Tomato','Cream','Spices'],
 ARRAY['Spinach/Keerai','Tomato','Onion'], ARRAY['Dairy'],
 '{"calories":390,"protein":"16g","carbs":"12g","fat":"30g"}', true,
 '[{"id":"a40-1","name":"Butter Naan","price":4,"isVeg":true},{"id":"a40-2","name":"Jeera Rice","price":4,"isVeg":true}]',
 true),

('m41','SKID-HOU-007','Sarson Ka Saag',
 'Mustard greens cooked with spices & ghee — Punjabi winter classic.',
 15, 9, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Sabzi', true, false, 'medium', '350 g', '30 min',
 ARRAY['Mustard Greens','Spinach','Ghee','Garlic','Ginger','Spices'],
 ARRAY['Spinach/Keerai','Garlic'], ARRAY['Dairy'],
 '{"calories":280,"protein":"8g","carbs":"18g","fat":"18g"}', true,
 '[{"id":"a41-1","name":"Makki Di Roti (2 pcs)","price":3,"isVeg":true}]',
 true),

-- SKID-SEA-008 : Radha's Kitchen (5 items)
('m12','SKID-SEA-008','Kerala Fish Curry',
 'Fresh fish simmered in a tangy coconut and raw mango curry — Kerala coastal style.',
 23, 15, 'https://images.unsplash.com/photo-1626776876729-bab4369a5a5a?w=600&h=400&fit=crop',
 'Curries', false, true, 'medium', 'Serves 1-2', '30 min',
 ARRAY['Fish','Coconut Milk','Raw Mango','Kokum','Curry Leaves','Spices'],
 ARRAY[]::text[], ARRAY['Fish','Coconut'],
 '{"calories":380,"protein":"28g","carbs":"10g","fat":"24g"}', true,
 '[{"id":"a12-1","name":"Steamed Rice","price":3,"isVeg":true}]',
 true),

('m13','SKID-SEA-008','Appam with Stew',
 'Lacy Kerala appam with coconut milk vegetable stew.',
 12, 8, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
 'Kerala', true, false, 'mild', '2 appams + stew', '20 min',
 ARRAY['Rice Flour','Coconut Milk','Mixed Vegetables'],
 ARRAY['Potato','Carrot','Beans'], ARRAY['Coconut'],
 '{"calories":340,"protein":"8g","carbs":"56g","fat":"10g"}', true,
 '[]',
 true),

('m42','SKID-SEA-008','Avial',
 'Classic Kerala mixed vegetable dish in coconut-yogurt gravy.',
 11, 7, 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=600&h=400&fit=crop',
 'Curry', true, false, 'mild', 'Serves 1-2 (450 ml)', '30 min',
 ARRAY['Drumstick','Carrot','Beans','Coconut','Yogurt','Curry Leaves'],
 ARRAY['Drumstick','Carrot','Beans','Coconut','Curd/Buttermilk'], ARRAY['Dairy','Coconut'],
 '{"calories":210,"protein":"5g","carbs":"24g","fat":"11g"}', true,
 '[]',
 true),

('m43','SKID-SEA-008','Olan',
 'Ash gourd and cowpeas cooked in coconut milk — simple, clean Kerala comfort food.',
 10, 6, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'Curry', true, false, 'mild', 'Serves 1-2 (450 ml)', '25 min',
 ARRAY['Ash Gourd','Cowpeas','Coconut Milk','Curry Leaves','Green Chili'],
 ARRAY['Coconut'], ARRAY['Coconut'],
 '{"calories":180,"protein":"5g","carbs":"22g","fat":"8g"}', true,
 '[]',
 true),

('m44','SKID-SEA-008','Thoran',
 'Dry stir-fried cabbage with freshly grated coconut — Kerala style.',
 9, 5, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Poriyal', true, false, 'mild', '250 g', '15 min',
 ARRAY['Cabbage','Coconut','Mustard Seeds','Curry Leaves','Green Chili'],
 ARRAY['Cabbage','Coconut'], ARRAY['Coconut'],
 '{"calories":140,"protein":"3g","carbs":"14g","fat":"8g"}', true,
 '[]',
 true),

-- SKID-DAL-009 : Shero Dallas Veg (5 items)
('m14','SKID-DAL-009','Chole Bhature',
 'Spicy chickpea curry with fluffy fried bhatura bread.',
 13, 8, 'https://images.unsplash.com/photo-1574484284002-952d92456975?w=600&h=400&fit=crop',
 'North Indian', true, true, 'medium', 'Serves 1', '20 min',
 ARRAY['Chickpeas','Flour','Onions','Tomatoes','Spices'],
 ARRAY['Onion','Tomato'], ARRAY['Gluten'],
 '{"calories":520,"protein":"16g","carbs":"62g","fat":"22g"}', true,
 '[]',
 true),

('m15','SKID-DAL-009','Dal Makhani',
 'Slow-cooked black lentils in creamy tomato gravy.',
 16, 10, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'North Indian', true, false, 'mild', 'Serves 1-2', '25 min',
 ARRAY['Black Lentils','Kidney Beans','Butter','Cream','Tomatoes'],
 ARRAY['Tomato'], ARRAY['Dairy'],
 '{"calories":440,"protein":"18g","carbs":"38g","fat":"24g"}', false,
 '[{"id":"a15-1","name":"Butter Naan","price":4,"isVeg":true}]',
 true),

('m45','SKID-DAL-009','Paneer Tikka Masala',
 'Grilled paneer cubes in a rich spiced tomato-onion masala.',
 20, 13, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
 'Curries', true, true, 'medium', 'Serves 1-2', '30 min',
 ARRAY['Paneer','Tomato','Onion','Capsicum','Cream','Spices'],
 ARRAY['Tomato','Onion','Capsicum'], ARRAY['Dairy'],
 '{"calories":490,"protein":"20g","carbs":"16g","fat":"36g"}', true,
 '[{"id":"a45-1","name":"Garlic Naan","price":4,"isVeg":true},{"id":"a45-2","name":"Jeera Rice","price":4,"isVeg":true}]',
 true),

('m46','SKID-DAL-009','Kadai Vegetables',
 'Crunchy mixed vegetables cooked with freshly ground kadai spices.',
 15, 9, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Sabzi', true, false, 'medium', '350 g', '20 min',
 ARRAY['Capsicum','Onion','Tomato','Paneer','Kadai Masala'],
 ARRAY['Capsicum','Onion','Tomato'], ARRAY['Dairy'],
 '{"calories":290,"protein":"10g","carbs":"20g","fat":"18g"}', true,
 '[]',
 true),

('m47','SKID-DAL-009','Methi Thepla',
 'Gujarati thin flatbread with fresh fenugreek leaves and spices.',
 10, 6, 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=400&fit=crop',
 'Bread', true, false, 'mild', '3 pieces', '20 min',
 ARRAY['Wheat Flour','Fenugreek Leaves','Yogurt','Spices'],
 ARRAY['Spinach/Keerai'], ARRAY['Dairy','Gluten'],
 '{"calories":270,"protein":"7g","carbs":"38g","fat":"9g"}', true,
 '[{"id":"a47-1","name":"Mango Pickle","price":1,"isVeg":true},{"id":"a47-2","name":"Curd","price":2,"isVeg":true}]',
 true),

-- SKID-NJ-010 : Fatima's Biryani House (5 items)
('m48','SKID-NJ-010','Mughlai Mutton Biryani',
 'Slow-dum-cooked mutton biryani with saffron, fried onions, and rose water.',
 32, 20, 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=400&fit=crop',
 'Biryani', false, true, 'medium', 'Serves 1-2', '45 min',
 ARRAY['Basmati Rice','Mutton','Saffron','Fried Onions','Whole Spices','Rose Water'],
 ARRAY['Onion','Mint'], ARRAY['Dairy'],
 '{"calories":720,"protein":"38g","carbs":"80g","fat":"26g"}', true,
 '[{"id":"a48-1","name":"Raita","price":2,"isVeg":true},{"id":"a48-2","name":"Mirchi Ka Salan","price":3,"isVeg":true},{"id":"a48-3","name":"Extra Mutton","price":8,"isVeg":false}]',
 true),

('m49','SKID-NJ-010','Shahi Paneer',
 'Paneer in a rich cashew-cream gravy — royal Mughlai style.',
 22, 14, 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&h=400&fit=crop',
 'Curry', true, false, 'mild', 'Serves 1-2', '25 min',
 ARRAY['Paneer','Cashews','Cream','Cardamom','Tomato','Onion'],
 ARRAY['Tomato','Onion'], ARRAY['Dairy','Nuts'],
 '{"calories":520,"protein":"18g","carbs":"16g","fat":"40g"}', true,
 '[{"id":"a49-1","name":"Butter Naan","price":4,"isVeg":true}]',
 true),

('m50','SKID-NJ-010','Chicken Seekh Kebab',
 'Juicy minced chicken kebabs grilled on a skewer with herbs and spices.',
 19, 12, 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop',
 'Kebab', false, true, 'medium', '4 pieces', '25 min',
 ARRAY['Minced Chicken','Onion','Green Chili','Coriander','Spices','Charcoal'],
 ARRAY['Onion'], ARRAY[]::text[],
 '{"calories":360,"protein":"28g","carbs":"8g","fat":"22g"}', true,
 '[{"id":"a50-1","name":"Mint Chutney","price":1,"isVeg":true},{"id":"a50-2","name":"Naan (2 pcs)","price":4,"isVeg":true}]',
 true),

('m51','SKID-NJ-010','Navratan Korma',
 'Mixed vegetables & dried fruits in a mild cream sauce — Mughlai vegetarian delight.',
 20, 13, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&h=400&fit=crop',
 'Curry', true, false, 'mild', 'Serves 1-2', '25 min',
 ARRAY['Mixed Vegetables','Cashews','Cream','Cardamom','Raisins','Paneer'],
 ARRAY['Carrot','Beans','Potato','Cauliflower'], ARRAY['Dairy','Nuts'],
 '{"calories":470,"protein":"12g","carbs":"28g","fat":"34g"}', true,
 '[{"id":"a51-1","name":"Butter Naan","price":4,"isVeg":true}]',
 true),

('m52','SKID-NJ-010','Dal Mughlai',
 'Lentils cooked with cream, butter, and Mughlai aromatic spices.',
 17, 10, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=400&fit=crop',
 'Dal', true, false, 'mild', 'Serves 1-2 (450 ml)', '25 min',
 ARRAY['Masoor Dal','Butter','Cream','Cardamom','Whole Spices'],
 ARRAY['Dal/Lentils','Tomato'], ARRAY['Dairy'],
 '{"calories":380,"protein":"14g","carbs":"34g","fat":"20g"}', true,
 '[{"id":"a52-1","name":"Paratha","price":3,"isVeg":true}]',
 true)

ON CONFLICT (id) DO UPDATE SET
  name             = EXCLUDED.name,
  description      = EXCLUDED.description,
  price            = EXCLUDED.price,
  ppp              = EXCLUDED.ppp,
  image            = EXCLUDED.image,
  category         = EXCLUDED.category,
  is_veg           = EXCLUDED.is_veg,
  is_bestseller    = EXCLUDED.is_bestseller,
  spice_level      = EXCLUDED.spice_level,
  serving_size     = EXCLUDED.serving_size,
  preparation_time = EXCLUDED.preparation_time,
  ingredients      = EXCLUDED.ingredients,
  major_vegetables = EXCLUDED.major_vegetables,
  allergens        = EXCLUDED.allergens,
  nutrition_info   = EXCLUDED.nutrition_info,
  is_toggled_on    = EXCLUDED.is_toggled_on,
  add_ons          = EXCLUDED.add_ons,
  is_active        = EXCLUDED.is_active;

-- ── 4. Kitchen Categories (per-kitchen rows for filter chips) ──────
-- The kitchen_categories table already exists with schema:
--   (id, kitchen_id, name, icon, display_order, is_active, ...)
-- UNIQUE constraint is (kitchen_id, name) — we insert per-kitchen categories.
INSERT INTO public.kitchen_categories (kitchen_id, name, display_order, is_active) VALUES
  -- SKID-NYC-001 Veg
  ('SKID-NYC-001','Rice',       1, true),
  ('SKID-NYC-001','Dosa',       2, true),
  ('SKID-NYC-001','Curries',    3, true),
  ('SKID-NYC-001','Sambar',     4, true),
  ('SKID-NYC-001','Kara Kuzhambu', 5, true),
  ('SKID-NYC-001','Poriyal',    6, true),
  -- SKID-NYC-002 NonVeg
  ('SKID-NYC-002','Biryani',    1, true),
  ('SKID-NYC-002','Curries',    2, true),
  ('SKID-NYC-002','Rice',       3, true),
  -- SKID-SF-003 Padma's
  ('SKID-SF-003','Rice',        1, true),
  ('SKID-SF-003','Dosa',        2, true),
  ('SKID-SF-003','Curry',       3, true),
  ('SKID-SF-003','Chutney',     4, true),
  -- SKID-AUS-004 Austin Veg
  ('SKID-AUS-004','Chinese',    1, true),
  ('SKID-AUS-004','Idli',       2, true),
  ('SKID-AUS-004','Rice',       3, true),
  ('SKID-AUS-004','Dal',        4, true),
  ('SKID-AUS-004','Sabzi',      5, true),
  -- SKID-AUS-005 Austin NonVeg
  ('SKID-AUS-005','Curries',    1, true),
  ('SKID-AUS-005','Fry',        2, true),
  ('SKID-AUS-005','Biryani',    3, true),
  -- SKID-CHI-006 Anitha's
  ('SKID-CHI-006','Curries',    1, true),
  ('SKID-CHI-006','Fry',        2, true),
  ('SKID-CHI-006','Dal',        3, true),
  ('SKID-CHI-006','Biryani',    4, true),
  ('SKID-CHI-006','Breakfast',  5, true),
  -- SKID-HOU-007 Houston Veg
  ('SKID-HOU-007','Paratha',    1, true),
  ('SKID-HOU-007','North Indian', 2, true),
  ('SKID-HOU-007','Curries',    3, true),
  ('SKID-HOU-007','Sabzi',      4, true),
  -- SKID-SEA-008 Radha's Kitchen
  ('SKID-SEA-008','Curries',    1, true),
  ('SKID-SEA-008','Kerala',     2, true),
  ('SKID-SEA-008','Curry',      3, true),
  ('SKID-SEA-008','Poriyal',    4, true),
  -- SKID-DAL-009 Dallas Veg
  ('SKID-DAL-009','North Indian', 1, true),
  ('SKID-DAL-009','Curries',    2, true),
  ('SKID-DAL-009','Sabzi',      3, true),
  ('SKID-DAL-009','Bread',      4, true),
  -- SKID-NJ-010 Fatima's
  ('SKID-NJ-010','Biryani',     1, true),
  ('SKID-NJ-010','Curry',       2, true),
  ('SKID-NJ-010','Kebab',       3, true),
  ('SKID-NJ-010','Dal',         4, true)
ON CONFLICT (kitchen_id, name) DO NOTHING;

-- ── 5. App Config ────────────────────────────────────────────────
INSERT INTO public.app_config (key, value) VALUES
  ('kitchen_visibility_radius', '{"radius_miles": 20}')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

INSERT INTO public.app_config (key, value) VALUES
  ('invoice_settings', '{"deliveryFee": "30", "tipPresets": "[5,10,15,20]", "platformFeePercent": "0"}')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
